version: "3"

services:
    www:
        build: .
        restart: always
        ports:
            - "8010:80"
        volumes:
            - ./www:/var/www/html
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: DB_NAME
            MYSQL_USER: DB_USER
            MYSQL_PASSWORD: DB_PASSWORD
            MYSQL_ROOT_PASSWORD: DB_PASSWORD
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

volumes:
    db_data:
